package edu.black.dao;

import edu.black.model.Cars;
import edu.black.model.CarsExample;
import java.util.List;

import edu.black.model.Store;
import org.apache.ibatis.annotations.Param;

public interface CarsMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    long countByExample(CarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int deleteByExample(CarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int deleteByPrimaryKey(Integer carid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int insert(Cars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int insertSelective(Cars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    List<Cars> selectByExample(CarsExample example);
    List<Cars> selectCarsDetail(Cars cars);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    Cars selectByPrimaryKey(Integer carid);
    Cars selectOneCar(Store store);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") Cars record, @Param("example") CarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByExample(@Param("record") Cars record, @Param("example") CarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByPrimaryKeySelective(Cars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByPrimaryKey(Cars record);
    List<String> getAllCarNames();
    List<String> getAllCarModel(String model);
    List<Integer> getAllCarNoByModel(String model);
    List<Integer> getAllCarNoByName(String name);
}