package edu.black.dao;

import edu.black.model.Clients;
import edu.black.model.ClientsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClientsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    long countByExample(ClientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int deleteByExample(ClientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int deleteByPrimaryKey(Integer clientid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int insert(Clients record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int insertSelective(Clients record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    List<Clients> selectByExample(ClientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    Clients selectByPrimaryKey(Integer clientid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") Clients record, @Param("example") ClientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByExample(@Param("record") Clients record, @Param("example") ClientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByPrimaryKeySelective(Clients record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByPrimaryKey(Clients record);
}