package edu.black.dao;

import edu.black.model.Factories;
import edu.black.model.FactoriesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FactoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    long countByExample(FactoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int deleteByExample(FactoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int deleteByPrimaryKey(Integer factoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int insert(Factories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int insertSelective(Factories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    List<Factories> selectByExample(FactoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    Factories selectByPrimaryKey(Integer factoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") Factories record, @Param("example") FactoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByExample(@Param("record") Factories record, @Param("example") FactoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByPrimaryKeySelective(Factories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByPrimaryKey(Factories record);
}