package edu.black.dao;

import edu.black.model.Feedbacks;
import edu.black.model.FeedbacksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeedbacksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    long countByExample(FeedbacksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int deleteByExample(FeedbacksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int deleteByPrimaryKey(Integer feedbackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int insert(Feedbacks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int insertSelective(Feedbacks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    List<Feedbacks> selectByExample(FeedbacksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    Feedbacks selectByPrimaryKey(Integer feedbackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") Feedbacks record, @Param("example") FeedbacksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByExample(@Param("record") Feedbacks record, @Param("example") FeedbacksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByPrimaryKeySelective(Feedbacks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedbacks
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByPrimaryKey(Feedbacks record);
}