package edu.black.dao;

import edu.black.model.Rolesauthority;
import edu.black.model.RolesauthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolesauthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolesauthority
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    long countByExample(RolesauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolesauthority
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int deleteByExample(RolesauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolesauthority
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int insert(Rolesauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolesauthority
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int insertSelective(Rolesauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolesauthority
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    List<Rolesauthority> selectByExample(RolesauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolesauthority
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") Rolesauthority record, @Param("example") RolesauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolesauthority
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByExample(@Param("record") Rolesauthority record, @Param("example") RolesauthorityExample example);
}