package edu.black.dao;

import edu.black.model.Usersrole;
import edu.black.model.UsersroleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersrole
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    long countByExample(UsersroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersrole
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int deleteByExample(UsersroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersrole
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int insert(Usersrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersrole
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int insertSelective(Usersrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersrole
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    List<Usersrole> selectByExample(UsersroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersrole
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") Usersrole record, @Param("example") UsersroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersrole
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    int updateByExample(@Param("record") Usersrole record, @Param("example") UsersroleExample example);
}