package edu.black.model;

public class Authority {
    private Integer authorityparentid;
    private Integer authoritylevel;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authorityId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer authorityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authorityName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String authorityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authorityAction
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String authorityaction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authorityId
     *
     * @return the value of authority.authorityId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getAuthorityid() {
        return authorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authorityId
     *
     * @param authorityid the value for authority.authorityId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setAuthorityid(Integer authorityid) {
        this.authorityid = authorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authorityName
     *
     * @return the value of authority.authorityName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getAuthorityname() {
        return authorityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authorityName
     *
     * @param authorityname the value for authority.authorityName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setAuthorityname(String authorityname) {
        this.authorityname = authorityname == null ? null : authorityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authorityAction
     *
     * @return the value of authority.authorityAction
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getAuthorityaction() {
        return authorityaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authorityAction
     *
     * @param authorityaction the value for authority.authorityAction
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setAuthorityaction(String authorityaction) {
        this.authorityaction = authorityaction == null ? null : authorityaction.trim();
    }

    public Integer getAuthorityparentid() {
        return authorityparentid;
    }

    public void setAuthorityparentid(Integer authorityparentid) {
        this.authorityparentid = authorityparentid;
    }

    public Integer getAuthoritylevel() {
        return authoritylevel;
    }

    public void setAuthoritylevel(Integer authoritylevel) {
        this.authoritylevel = authoritylevel;
    }
}