package edu.black.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CarsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public CarsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCaridIsNull() {
            addCriterion("carId is null");
            return (Criteria) this;
        }

        public Criteria andCaridIsNotNull() {
            addCriterion("carId is not null");
            return (Criteria) this;
        }

        public Criteria andCaridEqualTo(Integer value) {
            addCriterion("carId =", value, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridNotEqualTo(Integer value) {
            addCriterion("carId <>", value, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridGreaterThan(Integer value) {
            addCriterion("carId >", value, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridGreaterThanOrEqualTo(Integer value) {
            addCriterion("carId >=", value, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridLessThan(Integer value) {
            addCriterion("carId <", value, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridLessThanOrEqualTo(Integer value) {
            addCriterion("carId <=", value, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridIn(List<Integer> values) {
            addCriterion("carId in", values, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridNotIn(List<Integer> values) {
            addCriterion("carId not in", values, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridBetween(Integer value1, Integer value2) {
            addCriterion("carId between", value1, value2, "carid");
            return (Criteria) this;
        }

        public Criteria andCaridNotBetween(Integer value1, Integer value2) {
            addCriterion("carId not between", value1, value2, "carid");
            return (Criteria) this;
        }

        public Criteria andCarnoIsNull() {
            addCriterion("carNo is null");
            return (Criteria) this;
        }

        public Criteria andCarnoIsNotNull() {
            addCriterion("carNo is not null");
            return (Criteria) this;
        }

        public Criteria andCarnoEqualTo(String value) {
            addCriterion("carNo =", value, "carno");
            return (Criteria) this;
        }

        public Criteria andCarnoNotEqualTo(String value) {
            addCriterion("carNo <>", value, "carno");
            return (Criteria) this;
        }

        public Criteria andCarnoGreaterThan(String value) {
            addCriterion("carNo >", value, "carno");
            return (Criteria) this;
        }

        public Criteria andCarnoGreaterThanOrEqualTo(String value) {
            addCriterion("carNo >=", value, "carno");
            return (Criteria) this;
        }

        public Criteria andCarnoLessThan(String value) {
            addCriterion("carNo <", value, "carno");
            return (Criteria) this;
        }

        public Criteria andCarnoLessThanOrEqualTo(String value) {
            addCriterion("carNo <=", value, "carno");
            return (Criteria) this;
        }

        public Criteria andCarnoLike(String value) {
            addCriterion("carNo like", value, "carno");
            return (Criteria) this;
        }

        public Criteria andCarnoNotLike(String value) {
            addCriterion("carNo not like", value, "carno");
            return (Criteria) this;
        }

        public Criteria andCarnoIn(List<String> values) {
            addCriterion("carNo in", values, "carno");
            return (Criteria) this;
        }

        public Criteria andCarnoNotIn(List<String> values) {
            addCriterion("carNo not in", values, "carno");
            return (Criteria) this;
        }

        public Criteria andCarnoBetween(String value1, String value2) {
            addCriterion("carNo between", value1, value2, "carno");
            return (Criteria) this;
        }

        public Criteria andCarnoNotBetween(String value1, String value2) {
            addCriterion("carNo not between", value1, value2, "carno");
            return (Criteria) this;
        }

        public Criteria andCarnameIsNull() {
            addCriterion("carName is null");
            return (Criteria) this;
        }

        public Criteria andCarnameIsNotNull() {
            addCriterion("carName is not null");
            return (Criteria) this;
        }

        public Criteria andCarnameEqualTo(String value) {
            addCriterion("carName =", value, "carname");
            return (Criteria) this;
        }

        public Criteria andCarnameNotEqualTo(String value) {
            addCriterion("carName <>", value, "carname");
            return (Criteria) this;
        }

        public Criteria andCarnameGreaterThan(String value) {
            addCriterion("carName >", value, "carname");
            return (Criteria) this;
        }

        public Criteria andCarnameGreaterThanOrEqualTo(String value) {
            addCriterion("carName >=", value, "carname");
            return (Criteria) this;
        }

        public Criteria andCarnameLessThan(String value) {
            addCriterion("carName <", value, "carname");
            return (Criteria) this;
        }

        public Criteria andCarnameLessThanOrEqualTo(String value) {
            addCriterion("carName <=", value, "carname");
            return (Criteria) this;
        }

        public Criteria andCarnameLike(String value) {
            addCriterion("carName like", value, "carname");
            return (Criteria) this;
        }

        public Criteria andCarnameNotLike(String value) {
            addCriterion("carName not like", value, "carname");
            return (Criteria) this;
        }

        public Criteria andCarnameIn(List<String> values) {
            addCriterion("carName in", values, "carname");
            return (Criteria) this;
        }

        public Criteria andCarnameNotIn(List<String> values) {
            addCriterion("carName not in", values, "carname");
            return (Criteria) this;
        }

        public Criteria andCarnameBetween(String value1, String value2) {
            addCriterion("carName between", value1, value2, "carname");
            return (Criteria) this;
        }

        public Criteria andCarnameNotBetween(String value1, String value2) {
            addCriterion("carName not between", value1, value2, "carname");
            return (Criteria) this;
        }

        public Criteria andCarmodelIsNull() {
            addCriterion("carModel is null");
            return (Criteria) this;
        }

        public Criteria andCarmodelIsNotNull() {
            addCriterion("carModel is not null");
            return (Criteria) this;
        }

        public Criteria andCarmodelEqualTo(String value) {
            addCriterion("carModel =", value, "carmodel");
            return (Criteria) this;
        }

        public Criteria andCarmodelNotEqualTo(String value) {
            addCriterion("carModel <>", value, "carmodel");
            return (Criteria) this;
        }

        public Criteria andCarmodelGreaterThan(String value) {
            addCriterion("carModel >", value, "carmodel");
            return (Criteria) this;
        }

        public Criteria andCarmodelGreaterThanOrEqualTo(String value) {
            addCriterion("carModel >=", value, "carmodel");
            return (Criteria) this;
        }

        public Criteria andCarmodelLessThan(String value) {
            addCriterion("carModel <", value, "carmodel");
            return (Criteria) this;
        }

        public Criteria andCarmodelLessThanOrEqualTo(String value) {
            addCriterion("carModel <=", value, "carmodel");
            return (Criteria) this;
        }

        public Criteria andCarmodelLike(String value) {
            addCriterion("carModel like", value, "carmodel");
            return (Criteria) this;
        }

        public Criteria andCarmodelNotLike(String value) {
            addCriterion("carModel not like", value, "carmodel");
            return (Criteria) this;
        }

        public Criteria andCarmodelIn(List<String> values) {
            addCriterion("carModel in", values, "carmodel");
            return (Criteria) this;
        }

        public Criteria andCarmodelNotIn(List<String> values) {
            addCriterion("carModel not in", values, "carmodel");
            return (Criteria) this;
        }

        public Criteria andCarmodelBetween(String value1, String value2) {
            addCriterion("carModel between", value1, value2, "carmodel");
            return (Criteria) this;
        }

        public Criteria andCarmodelNotBetween(String value1, String value2) {
            addCriterion("carModel not between", value1, value2, "carmodel");
            return (Criteria) this;
        }

        public Criteria andCarcolorIsNull() {
            addCriterion("carColor is null");
            return (Criteria) this;
        }

        public Criteria andCarcolorIsNotNull() {
            addCriterion("carColor is not null");
            return (Criteria) this;
        }

        public Criteria andCarcolorEqualTo(String value) {
            addCriterion("carColor =", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorNotEqualTo(String value) {
            addCriterion("carColor <>", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorGreaterThan(String value) {
            addCriterion("carColor >", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorGreaterThanOrEqualTo(String value) {
            addCriterion("carColor >=", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorLessThan(String value) {
            addCriterion("carColor <", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorLessThanOrEqualTo(String value) {
            addCriterion("carColor <=", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorLike(String value) {
            addCriterion("carColor like", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorNotLike(String value) {
            addCriterion("carColor not like", value, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorIn(List<String> values) {
            addCriterion("carColor in", values, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorNotIn(List<String> values) {
            addCriterion("carColor not in", values, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorBetween(String value1, String value2) {
            addCriterion("carColor between", value1, value2, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarcolorNotBetween(String value1, String value2) {
            addCriterion("carColor not between", value1, value2, "carcolor");
            return (Criteria) this;
        }

        public Criteria andCarmobileIsNull() {
            addCriterion("carMobile is null");
            return (Criteria) this;
        }

        public Criteria andCarmobileIsNotNull() {
            addCriterion("carMobile is not null");
            return (Criteria) this;
        }

        public Criteria andCarmobileEqualTo(String value) {
            addCriterion("carMobile =", value, "carmobile");
            return (Criteria) this;
        }

        public Criteria andCarmobileNotEqualTo(String value) {
            addCriterion("carMobile <>", value, "carmobile");
            return (Criteria) this;
        }

        public Criteria andCarmobileGreaterThan(String value) {
            addCriterion("carMobile >", value, "carmobile");
            return (Criteria) this;
        }

        public Criteria andCarmobileGreaterThanOrEqualTo(String value) {
            addCriterion("carMobile >=", value, "carmobile");
            return (Criteria) this;
        }

        public Criteria andCarmobileLessThan(String value) {
            addCriterion("carMobile <", value, "carmobile");
            return (Criteria) this;
        }

        public Criteria andCarmobileLessThanOrEqualTo(String value) {
            addCriterion("carMobile <=", value, "carmobile");
            return (Criteria) this;
        }

        public Criteria andCarmobileLike(String value) {
            addCriterion("carMobile like", value, "carmobile");
            return (Criteria) this;
        }

        public Criteria andCarmobileNotLike(String value) {
            addCriterion("carMobile not like", value, "carmobile");
            return (Criteria) this;
        }

        public Criteria andCarmobileIn(List<String> values) {
            addCriterion("carMobile in", values, "carmobile");
            return (Criteria) this;
        }

        public Criteria andCarmobileNotIn(List<String> values) {
            addCriterion("carMobile not in", values, "carmobile");
            return (Criteria) this;
        }

        public Criteria andCarmobileBetween(String value1, String value2) {
            addCriterion("carMobile between", value1, value2, "carmobile");
            return (Criteria) this;
        }

        public Criteria andCarmobileNotBetween(String value1, String value2) {
            addCriterion("carMobile not between", value1, value2, "carmobile");
            return (Criteria) this;
        }

        public Criteria andCarfromIsNull() {
            addCriterion("carFrom is null");
            return (Criteria) this;
        }

        public Criteria andCarfromIsNotNull() {
            addCriterion("carFrom is not null");
            return (Criteria) this;
        }

        public Criteria andCarfromEqualTo(String value) {
            addCriterion("carFrom =", value, "carfrom");
            return (Criteria) this;
        }

        public Criteria andCarfromNotEqualTo(String value) {
            addCriterion("carFrom <>", value, "carfrom");
            return (Criteria) this;
        }

        public Criteria andCarfromGreaterThan(String value) {
            addCriterion("carFrom >", value, "carfrom");
            return (Criteria) this;
        }

        public Criteria andCarfromGreaterThanOrEqualTo(String value) {
            addCriterion("carFrom >=", value, "carfrom");
            return (Criteria) this;
        }

        public Criteria andCarfromLessThan(String value) {
            addCriterion("carFrom <", value, "carfrom");
            return (Criteria) this;
        }

        public Criteria andCarfromLessThanOrEqualTo(String value) {
            addCriterion("carFrom <=", value, "carfrom");
            return (Criteria) this;
        }

        public Criteria andCarfromLike(String value) {
            addCriterion("carFrom like", value, "carfrom");
            return (Criteria) this;
        }

        public Criteria andCarfromNotLike(String value) {
            addCriterion("carFrom not like", value, "carfrom");
            return (Criteria) this;
        }

        public Criteria andCarfromIn(List<String> values) {
            addCriterion("carFrom in", values, "carfrom");
            return (Criteria) this;
        }

        public Criteria andCarfromNotIn(List<String> values) {
            addCriterion("carFrom not in", values, "carfrom");
            return (Criteria) this;
        }

        public Criteria andCarfromBetween(String value1, String value2) {
            addCriterion("carFrom between", value1, value2, "carfrom");
            return (Criteria) this;
        }

        public Criteria andCarfromNotBetween(String value1, String value2) {
            addCriterion("carFrom not between", value1, value2, "carfrom");
            return (Criteria) this;
        }

        public Criteria andCarcreatedateIsNull() {
            addCriterion("carCreateDate is null");
            return (Criteria) this;
        }

        public Criteria andCarcreatedateIsNotNull() {
            addCriterion("carCreateDate is not null");
            return (Criteria) this;
        }

        public Criteria andCarcreatedateEqualTo(Date value) {
            addCriterion("carCreateDate =", value, "carcreatedate");
            return (Criteria) this;
        }

        public Criteria andCarcreatedateNotEqualTo(Date value) {
            addCriterion("carCreateDate <>", value, "carcreatedate");
            return (Criteria) this;
        }

        public Criteria andCarcreatedateGreaterThan(Date value) {
            addCriterion("carCreateDate >", value, "carcreatedate");
            return (Criteria) this;
        }

        public Criteria andCarcreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("carCreateDate >=", value, "carcreatedate");
            return (Criteria) this;
        }

        public Criteria andCarcreatedateLessThan(Date value) {
            addCriterion("carCreateDate <", value, "carcreatedate");
            return (Criteria) this;
        }

        public Criteria andCarcreatedateLessThanOrEqualTo(Date value) {
            addCriterion("carCreateDate <=", value, "carcreatedate");
            return (Criteria) this;
        }

        public Criteria andCarcreatedateIn(List<Date> values) {
            addCriterion("carCreateDate in", values, "carcreatedate");
            return (Criteria) this;
        }

        public Criteria andCarcreatedateNotIn(List<Date> values) {
            addCriterion("carCreateDate not in", values, "carcreatedate");
            return (Criteria) this;
        }

        public Criteria andCarcreatedateBetween(Date value1, Date value2) {
            addCriterion("carCreateDate between", value1, value2, "carcreatedate");
            return (Criteria) this;
        }

        public Criteria andCarcreatedateNotBetween(Date value1, Date value2) {
            addCriterion("carCreateDate not between", value1, value2, "carcreatedate");
            return (Criteria) this;
        }

        public Criteria andCarindateIsNull() {
            addCriterion("carInDate is null");
            return (Criteria) this;
        }

        public Criteria andCarindateIsNotNull() {
            addCriterion("carInDate is not null");
            return (Criteria) this;
        }

        public Criteria andCarindateEqualTo(Date value) {
            addCriterion("carInDate =", value, "carindate");
            return (Criteria) this;
        }

        public Criteria andCarindateNotEqualTo(Date value) {
            addCriterion("carInDate <>", value, "carindate");
            return (Criteria) this;
        }

        public Criteria andCarindateGreaterThan(Date value) {
            addCriterion("carInDate >", value, "carindate");
            return (Criteria) this;
        }

        public Criteria andCarindateGreaterThanOrEqualTo(Date value) {
            addCriterion("carInDate >=", value, "carindate");
            return (Criteria) this;
        }

        public Criteria andCarindateLessThan(Date value) {
            addCriterion("carInDate <", value, "carindate");
            return (Criteria) this;
        }

        public Criteria andCarindateLessThanOrEqualTo(Date value) {
            addCriterion("carInDate <=", value, "carindate");
            return (Criteria) this;
        }

        public Criteria andCarindateIn(List<Date> values) {
            addCriterion("carInDate in", values, "carindate");
            return (Criteria) this;
        }

        public Criteria andCarindateNotIn(List<Date> values) {
            addCriterion("carInDate not in", values, "carindate");
            return (Criteria) this;
        }

        public Criteria andCarindateBetween(Date value1, Date value2) {
            addCriterion("carInDate between", value1, value2, "carindate");
            return (Criteria) this;
        }

        public Criteria andCarindateNotBetween(Date value1, Date value2) {
            addCriterion("carInDate not between", value1, value2, "carindate");
            return (Criteria) this;
        }

        public Criteria andCardescriptionIsNull() {
            addCriterion("carDescription is null");
            return (Criteria) this;
        }

        public Criteria andCardescriptionIsNotNull() {
            addCriterion("carDescription is not null");
            return (Criteria) this;
        }

        public Criteria andCardescriptionEqualTo(String value) {
            addCriterion("carDescription =", value, "cardescription");
            return (Criteria) this;
        }

        public Criteria andCardescriptionNotEqualTo(String value) {
            addCriterion("carDescription <>", value, "cardescription");
            return (Criteria) this;
        }

        public Criteria andCardescriptionGreaterThan(String value) {
            addCriterion("carDescription >", value, "cardescription");
            return (Criteria) this;
        }

        public Criteria andCardescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("carDescription >=", value, "cardescription");
            return (Criteria) this;
        }

        public Criteria andCardescriptionLessThan(String value) {
            addCriterion("carDescription <", value, "cardescription");
            return (Criteria) this;
        }

        public Criteria andCardescriptionLessThanOrEqualTo(String value) {
            addCriterion("carDescription <=", value, "cardescription");
            return (Criteria) this;
        }

        public Criteria andCardescriptionLike(String value) {
            addCriterion("carDescription like", value, "cardescription");
            return (Criteria) this;
        }

        public Criteria andCardescriptionNotLike(String value) {
            addCriterion("carDescription not like", value, "cardescription");
            return (Criteria) this;
        }

        public Criteria andCardescriptionIn(List<String> values) {
            addCriterion("carDescription in", values, "cardescription");
            return (Criteria) this;
        }

        public Criteria andCardescriptionNotIn(List<String> values) {
            addCriterion("carDescription not in", values, "cardescription");
            return (Criteria) this;
        }

        public Criteria andCardescriptionBetween(String value1, String value2) {
            addCriterion("carDescription between", value1, value2, "cardescription");
            return (Criteria) this;
        }

        public Criteria andCardescriptionNotBetween(String value1, String value2) {
            addCriterion("carDescription not between", value1, value2, "cardescription");
            return (Criteria) this;
        }

        public Criteria andCartoIsNull() {
            addCriterion("carTo is null");
            return (Criteria) this;
        }

        public Criteria andCartoIsNotNull() {
            addCriterion("carTo is not null");
            return (Criteria) this;
        }

        public Criteria andCartoEqualTo(String value) {
            addCriterion("carTo =", value, "carto");
            return (Criteria) this;
        }

        public Criteria andCartoNotEqualTo(String value) {
            addCriterion("carTo <>", value, "carto");
            return (Criteria) this;
        }

        public Criteria andCartoGreaterThan(String value) {
            addCriterion("carTo >", value, "carto");
            return (Criteria) this;
        }

        public Criteria andCartoGreaterThanOrEqualTo(String value) {
            addCriterion("carTo >=", value, "carto");
            return (Criteria) this;
        }

        public Criteria andCartoLessThan(String value) {
            addCriterion("carTo <", value, "carto");
            return (Criteria) this;
        }

        public Criteria andCartoLessThanOrEqualTo(String value) {
            addCriterion("carTo <=", value, "carto");
            return (Criteria) this;
        }

        public Criteria andCartoLike(String value) {
            addCriterion("carTo like", value, "carto");
            return (Criteria) this;
        }

        public Criteria andCartoNotLike(String value) {
            addCriterion("carTo not like", value, "carto");
            return (Criteria) this;
        }

        public Criteria andCartoIn(List<String> values) {
            addCriterion("carTo in", values, "carto");
            return (Criteria) this;
        }

        public Criteria andCartoNotIn(List<String> values) {
            addCriterion("carTo not in", values, "carto");
            return (Criteria) this;
        }

        public Criteria andCartoBetween(String value1, String value2) {
            addCriterion("carTo between", value1, value2, "carto");
            return (Criteria) this;
        }

        public Criteria andCartoNotBetween(String value1, String value2) {
            addCriterion("carTo not between", value1, value2, "carto");
            return (Criteria) this;
        }

        public Criteria andFactoryidIsNull() {
            addCriterion("factoryId is null");
            return (Criteria) this;
        }

        public Criteria andFactoryidIsNotNull() {
            addCriterion("factoryId is not null");
            return (Criteria) this;
        }

        public Criteria andFactoryidEqualTo(Integer value) {
            addCriterion("factoryId =", value, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidNotEqualTo(Integer value) {
            addCriterion("factoryId <>", value, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidGreaterThan(Integer value) {
            addCriterion("factoryId >", value, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidGreaterThanOrEqualTo(Integer value) {
            addCriterion("factoryId >=", value, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidLessThan(Integer value) {
            addCriterion("factoryId <", value, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidLessThanOrEqualTo(Integer value) {
            addCriterion("factoryId <=", value, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidIn(List<Integer> values) {
            addCriterion("factoryId in", values, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidNotIn(List<Integer> values) {
            addCriterion("factoryId not in", values, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidBetween(Integer value1, Integer value2) {
            addCriterion("factoryId between", value1, value2, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidNotBetween(Integer value1, Integer value2) {
            addCriterion("factoryId not between", value1, value2, "factoryid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cars
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 16 21:19:55 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cars
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}