package edu.black.model;

import java.util.Date;

public class Cars {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.carId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer carid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.carNo
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String carno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.carName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String carname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.carModel
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String carmodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.carColor
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String carcolor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.carMobile
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String carmobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.carFrom
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String carfrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.carCreateDate
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Date carcreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.carInDate
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Date carindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.carDescription
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String cardescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.carTo
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String carto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.factoryId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer factoryid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.carId
     *
     * @return the value of cars.carId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.carId
     *
     * @param carid the value for cars.carId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setCarid(Integer carid) {
        this.carid = carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.carNo
     *
     * @return the value of cars.carNo
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getCarno() {
        return carno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.carNo
     *
     * @param carno the value for cars.carNo
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setCarno(String carno) {
        this.carno = carno == null ? null : carno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.carName
     *
     * @return the value of cars.carName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getCarname() {
        return carname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.carName
     *
     * @param carname the value for cars.carName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setCarname(String carname) {
        this.carname = carname == null ? null : carname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.carModel
     *
     * @return the value of cars.carModel
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getCarmodel() {
        return carmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.carModel
     *
     * @param carmodel the value for cars.carModel
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setCarmodel(String carmodel) {
        this.carmodel = carmodel == null ? null : carmodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.carColor
     *
     * @return the value of cars.carColor
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getCarcolor() {
        return carcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.carColor
     *
     * @param carcolor the value for cars.carColor
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setCarcolor(String carcolor) {
        this.carcolor = carcolor == null ? null : carcolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.carMobile
     *
     * @return the value of cars.carMobile
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getCarmobile() {
        return carmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.carMobile
     *
     * @param carmobile the value for cars.carMobile
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setCarmobile(String carmobile) {
        this.carmobile = carmobile == null ? null : carmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.carFrom
     *
     * @return the value of cars.carFrom
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getCarfrom() {
        return carfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.carFrom
     *
     * @param carfrom the value for cars.carFrom
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setCarfrom(String carfrom) {
        this.carfrom = carfrom == null ? null : carfrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.carCreateDate
     *
     * @return the value of cars.carCreateDate
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Date getCarcreatedate() {
        return carcreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.carCreateDate
     *
     * @param carcreatedate the value for cars.carCreateDate
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setCarcreatedate(Date carcreatedate) {
        this.carcreatedate = carcreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.carInDate
     *
     * @return the value of cars.carInDate
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Date getCarindate() {
        return carindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.carInDate
     *
     * @param carindate the value for cars.carInDate
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setCarindate(Date carindate) {
        this.carindate = carindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.carDescription
     *
     * @return the value of cars.carDescription
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getCardescription() {
        return cardescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.carDescription
     *
     * @param cardescription the value for cars.carDescription
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setCardescription(String cardescription) {
        this.cardescription = cardescription == null ? null : cardescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.carTo
     *
     * @return the value of cars.carTo
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getCarto() {
        return carto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.carTo
     *
     * @param carto the value for cars.carTo
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setCarto(String carto) {
        this.carto = carto == null ? null : carto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.factoryId
     *
     * @return the value of cars.factoryId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getFactoryid() {
        return factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.factoryId
     *
     * @param factoryid the value for cars.factoryId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setFactoryid(Integer factoryid) {
        this.factoryid = factoryid;
    }
}