package edu.black.model;

public class Clients {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.clientId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.clientNo
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String clientno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.clientName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String clientname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.clientGender
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String clientgender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.clientTel
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String clienttel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.clientIdCard
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String clientidcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clients.clientAddress
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String clientaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.clientId
     *
     * @return the value of clients.clientId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.clientId
     *
     * @param clientid the value for clients.clientId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.clientNo
     *
     * @return the value of clients.clientNo
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getClientno() {
        return clientno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.clientNo
     *
     * @param clientno the value for clients.clientNo
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setClientno(String clientno) {
        this.clientno = clientno == null ? null : clientno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.clientName
     *
     * @return the value of clients.clientName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getClientname() {
        return clientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.clientName
     *
     * @param clientname the value for clients.clientName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setClientname(String clientname) {
        this.clientname = clientname == null ? null : clientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.clientGender
     *
     * @return the value of clients.clientGender
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getClientgender() {
        return clientgender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.clientGender
     *
     * @param clientgender the value for clients.clientGender
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setClientgender(String clientgender) {
        this.clientgender = clientgender == null ? null : clientgender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.clientTel
     *
     * @return the value of clients.clientTel
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getClienttel() {
        return clienttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.clientTel
     *
     * @param clienttel the value for clients.clientTel
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setClienttel(String clienttel) {
        this.clienttel = clienttel == null ? null : clienttel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.clientIdCard
     *
     * @return the value of clients.clientIdCard
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getClientidcard() {
        return clientidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.clientIdCard
     *
     * @param clientidcard the value for clients.clientIdCard
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setClientidcard(String clientidcard) {
        this.clientidcard = clientidcard == null ? null : clientidcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clients.clientAddress
     *
     * @return the value of clients.clientAddress
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getClientaddress() {
        return clientaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clients.clientAddress
     *
     * @param clientaddress the value for clients.clientAddress
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setClientaddress(String clientaddress) {
        this.clientaddress = clientaddress == null ? null : clientaddress.trim();
    }
}