package edu.black.model;

import java.util.ArrayList;
import java.util.List;

public class ClientsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public ClientsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClientidIsNull() {
            addCriterion("clientId is null");
            return (Criteria) this;
        }

        public Criteria andClientidIsNotNull() {
            addCriterion("clientId is not null");
            return (Criteria) this;
        }

        public Criteria andClientidEqualTo(Integer value) {
            addCriterion("clientId =", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotEqualTo(Integer value) {
            addCriterion("clientId <>", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidGreaterThan(Integer value) {
            addCriterion("clientId >", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidGreaterThanOrEqualTo(Integer value) {
            addCriterion("clientId >=", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidLessThan(Integer value) {
            addCriterion("clientId <", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidLessThanOrEqualTo(Integer value) {
            addCriterion("clientId <=", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidIn(List<Integer> values) {
            addCriterion("clientId in", values, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotIn(List<Integer> values) {
            addCriterion("clientId not in", values, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidBetween(Integer value1, Integer value2) {
            addCriterion("clientId between", value1, value2, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotBetween(Integer value1, Integer value2) {
            addCriterion("clientId not between", value1, value2, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientnoIsNull() {
            addCriterion("clientNo is null");
            return (Criteria) this;
        }

        public Criteria andClientnoIsNotNull() {
            addCriterion("clientNo is not null");
            return (Criteria) this;
        }

        public Criteria andClientnoEqualTo(String value) {
            addCriterion("clientNo =", value, "clientno");
            return (Criteria) this;
        }

        public Criteria andClientnoNotEqualTo(String value) {
            addCriterion("clientNo <>", value, "clientno");
            return (Criteria) this;
        }

        public Criteria andClientnoGreaterThan(String value) {
            addCriterion("clientNo >", value, "clientno");
            return (Criteria) this;
        }

        public Criteria andClientnoGreaterThanOrEqualTo(String value) {
            addCriterion("clientNo >=", value, "clientno");
            return (Criteria) this;
        }

        public Criteria andClientnoLessThan(String value) {
            addCriterion("clientNo <", value, "clientno");
            return (Criteria) this;
        }

        public Criteria andClientnoLessThanOrEqualTo(String value) {
            addCriterion("clientNo <=", value, "clientno");
            return (Criteria) this;
        }

        public Criteria andClientnoLike(String value) {
            addCriterion("clientNo like", value, "clientno");
            return (Criteria) this;
        }

        public Criteria andClientnoNotLike(String value) {
            addCriterion("clientNo not like", value, "clientno");
            return (Criteria) this;
        }

        public Criteria andClientnoIn(List<String> values) {
            addCriterion("clientNo in", values, "clientno");
            return (Criteria) this;
        }

        public Criteria andClientnoNotIn(List<String> values) {
            addCriterion("clientNo not in", values, "clientno");
            return (Criteria) this;
        }

        public Criteria andClientnoBetween(String value1, String value2) {
            addCriterion("clientNo between", value1, value2, "clientno");
            return (Criteria) this;
        }

        public Criteria andClientnoNotBetween(String value1, String value2) {
            addCriterion("clientNo not between", value1, value2, "clientno");
            return (Criteria) this;
        }

        public Criteria andClientnameIsNull() {
            addCriterion("clientName is null");
            return (Criteria) this;
        }

        public Criteria andClientnameIsNotNull() {
            addCriterion("clientName is not null");
            return (Criteria) this;
        }

        public Criteria andClientnameEqualTo(String value) {
            addCriterion("clientName =", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameNotEqualTo(String value) {
            addCriterion("clientName <>", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameGreaterThan(String value) {
            addCriterion("clientName >", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameGreaterThanOrEqualTo(String value) {
            addCriterion("clientName >=", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameLessThan(String value) {
            addCriterion("clientName <", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameLessThanOrEqualTo(String value) {
            addCriterion("clientName <=", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameLike(String value) {
            addCriterion("clientName like", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameNotLike(String value) {
            addCriterion("clientName not like", value, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameIn(List<String> values) {
            addCriterion("clientName in", values, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameNotIn(List<String> values) {
            addCriterion("clientName not in", values, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameBetween(String value1, String value2) {
            addCriterion("clientName between", value1, value2, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientnameNotBetween(String value1, String value2) {
            addCriterion("clientName not between", value1, value2, "clientname");
            return (Criteria) this;
        }

        public Criteria andClientgenderIsNull() {
            addCriterion("clientGender is null");
            return (Criteria) this;
        }

        public Criteria andClientgenderIsNotNull() {
            addCriterion("clientGender is not null");
            return (Criteria) this;
        }

        public Criteria andClientgenderEqualTo(String value) {
            addCriterion("clientGender =", value, "clientgender");
            return (Criteria) this;
        }

        public Criteria andClientgenderNotEqualTo(String value) {
            addCriterion("clientGender <>", value, "clientgender");
            return (Criteria) this;
        }

        public Criteria andClientgenderGreaterThan(String value) {
            addCriterion("clientGender >", value, "clientgender");
            return (Criteria) this;
        }

        public Criteria andClientgenderGreaterThanOrEqualTo(String value) {
            addCriterion("clientGender >=", value, "clientgender");
            return (Criteria) this;
        }

        public Criteria andClientgenderLessThan(String value) {
            addCriterion("clientGender <", value, "clientgender");
            return (Criteria) this;
        }

        public Criteria andClientgenderLessThanOrEqualTo(String value) {
            addCriterion("clientGender <=", value, "clientgender");
            return (Criteria) this;
        }

        public Criteria andClientgenderLike(String value) {
            addCriterion("clientGender like", value, "clientgender");
            return (Criteria) this;
        }

        public Criteria andClientgenderNotLike(String value) {
            addCriterion("clientGender not like", value, "clientgender");
            return (Criteria) this;
        }

        public Criteria andClientgenderIn(List<String> values) {
            addCriterion("clientGender in", values, "clientgender");
            return (Criteria) this;
        }

        public Criteria andClientgenderNotIn(List<String> values) {
            addCriterion("clientGender not in", values, "clientgender");
            return (Criteria) this;
        }

        public Criteria andClientgenderBetween(String value1, String value2) {
            addCriterion("clientGender between", value1, value2, "clientgender");
            return (Criteria) this;
        }

        public Criteria andClientgenderNotBetween(String value1, String value2) {
            addCriterion("clientGender not between", value1, value2, "clientgender");
            return (Criteria) this;
        }

        public Criteria andClienttelIsNull() {
            addCriterion("clientTel is null");
            return (Criteria) this;
        }

        public Criteria andClienttelIsNotNull() {
            addCriterion("clientTel is not null");
            return (Criteria) this;
        }

        public Criteria andClienttelEqualTo(String value) {
            addCriterion("clientTel =", value, "clienttel");
            return (Criteria) this;
        }

        public Criteria andClienttelNotEqualTo(String value) {
            addCriterion("clientTel <>", value, "clienttel");
            return (Criteria) this;
        }

        public Criteria andClienttelGreaterThan(String value) {
            addCriterion("clientTel >", value, "clienttel");
            return (Criteria) this;
        }

        public Criteria andClienttelGreaterThanOrEqualTo(String value) {
            addCriterion("clientTel >=", value, "clienttel");
            return (Criteria) this;
        }

        public Criteria andClienttelLessThan(String value) {
            addCriterion("clientTel <", value, "clienttel");
            return (Criteria) this;
        }

        public Criteria andClienttelLessThanOrEqualTo(String value) {
            addCriterion("clientTel <=", value, "clienttel");
            return (Criteria) this;
        }

        public Criteria andClienttelLike(String value) {
            addCriterion("clientTel like", value, "clienttel");
            return (Criteria) this;
        }

        public Criteria andClienttelNotLike(String value) {
            addCriterion("clientTel not like", value, "clienttel");
            return (Criteria) this;
        }

        public Criteria andClienttelIn(List<String> values) {
            addCriterion("clientTel in", values, "clienttel");
            return (Criteria) this;
        }

        public Criteria andClienttelNotIn(List<String> values) {
            addCriterion("clientTel not in", values, "clienttel");
            return (Criteria) this;
        }

        public Criteria andClienttelBetween(String value1, String value2) {
            addCriterion("clientTel between", value1, value2, "clienttel");
            return (Criteria) this;
        }

        public Criteria andClienttelNotBetween(String value1, String value2) {
            addCriterion("clientTel not between", value1, value2, "clienttel");
            return (Criteria) this;
        }

        public Criteria andClientidcardIsNull() {
            addCriterion("clientIdCard is null");
            return (Criteria) this;
        }

        public Criteria andClientidcardIsNotNull() {
            addCriterion("clientIdCard is not null");
            return (Criteria) this;
        }

        public Criteria andClientidcardEqualTo(String value) {
            addCriterion("clientIdCard =", value, "clientidcard");
            return (Criteria) this;
        }

        public Criteria andClientidcardNotEqualTo(String value) {
            addCriterion("clientIdCard <>", value, "clientidcard");
            return (Criteria) this;
        }

        public Criteria andClientidcardGreaterThan(String value) {
            addCriterion("clientIdCard >", value, "clientidcard");
            return (Criteria) this;
        }

        public Criteria andClientidcardGreaterThanOrEqualTo(String value) {
            addCriterion("clientIdCard >=", value, "clientidcard");
            return (Criteria) this;
        }

        public Criteria andClientidcardLessThan(String value) {
            addCriterion("clientIdCard <", value, "clientidcard");
            return (Criteria) this;
        }

        public Criteria andClientidcardLessThanOrEqualTo(String value) {
            addCriterion("clientIdCard <=", value, "clientidcard");
            return (Criteria) this;
        }

        public Criteria andClientidcardLike(String value) {
            addCriterion("clientIdCard like", value, "clientidcard");
            return (Criteria) this;
        }

        public Criteria andClientidcardNotLike(String value) {
            addCriterion("clientIdCard not like", value, "clientidcard");
            return (Criteria) this;
        }

        public Criteria andClientidcardIn(List<String> values) {
            addCriterion("clientIdCard in", values, "clientidcard");
            return (Criteria) this;
        }

        public Criteria andClientidcardNotIn(List<String> values) {
            addCriterion("clientIdCard not in", values, "clientidcard");
            return (Criteria) this;
        }

        public Criteria andClientidcardBetween(String value1, String value2) {
            addCriterion("clientIdCard between", value1, value2, "clientidcard");
            return (Criteria) this;
        }

        public Criteria andClientidcardNotBetween(String value1, String value2) {
            addCriterion("clientIdCard not between", value1, value2, "clientidcard");
            return (Criteria) this;
        }

        public Criteria andClientaddressIsNull() {
            addCriterion("clientAddress is null");
            return (Criteria) this;
        }

        public Criteria andClientaddressIsNotNull() {
            addCriterion("clientAddress is not null");
            return (Criteria) this;
        }

        public Criteria andClientaddressEqualTo(String value) {
            addCriterion("clientAddress =", value, "clientaddress");
            return (Criteria) this;
        }

        public Criteria andClientaddressNotEqualTo(String value) {
            addCriterion("clientAddress <>", value, "clientaddress");
            return (Criteria) this;
        }

        public Criteria andClientaddressGreaterThan(String value) {
            addCriterion("clientAddress >", value, "clientaddress");
            return (Criteria) this;
        }

        public Criteria andClientaddressGreaterThanOrEqualTo(String value) {
            addCriterion("clientAddress >=", value, "clientaddress");
            return (Criteria) this;
        }

        public Criteria andClientaddressLessThan(String value) {
            addCriterion("clientAddress <", value, "clientaddress");
            return (Criteria) this;
        }

        public Criteria andClientaddressLessThanOrEqualTo(String value) {
            addCriterion("clientAddress <=", value, "clientaddress");
            return (Criteria) this;
        }

        public Criteria andClientaddressLike(String value) {
            addCriterion("clientAddress like", value, "clientaddress");
            return (Criteria) this;
        }

        public Criteria andClientaddressNotLike(String value) {
            addCriterion("clientAddress not like", value, "clientaddress");
            return (Criteria) this;
        }

        public Criteria andClientaddressIn(List<String> values) {
            addCriterion("clientAddress in", values, "clientaddress");
            return (Criteria) this;
        }

        public Criteria andClientaddressNotIn(List<String> values) {
            addCriterion("clientAddress not in", values, "clientaddress");
            return (Criteria) this;
        }

        public Criteria andClientaddressBetween(String value1, String value2) {
            addCriterion("clientAddress between", value1, value2, "clientaddress");
            return (Criteria) this;
        }

        public Criteria andClientaddressNotBetween(String value1, String value2) {
            addCriterion("clientAddress not between", value1, value2, "clientaddress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clients
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 16 21:19:55 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clients
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}