package edu.black.model;

import java.util.ArrayList;
import java.util.List;

public class FactoriesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public FactoriesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFactoryidIsNull() {
            addCriterion("factoryId is null");
            return (Criteria) this;
        }

        public Criteria andFactoryidIsNotNull() {
            addCriterion("factoryId is not null");
            return (Criteria) this;
        }

        public Criteria andFactoryidEqualTo(Integer value) {
            addCriterion("factoryId =", value, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidNotEqualTo(Integer value) {
            addCriterion("factoryId <>", value, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidGreaterThan(Integer value) {
            addCriterion("factoryId >", value, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidGreaterThanOrEqualTo(Integer value) {
            addCriterion("factoryId >=", value, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidLessThan(Integer value) {
            addCriterion("factoryId <", value, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidLessThanOrEqualTo(Integer value) {
            addCriterion("factoryId <=", value, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidIn(List<Integer> values) {
            addCriterion("factoryId in", values, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidNotIn(List<Integer> values) {
            addCriterion("factoryId not in", values, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidBetween(Integer value1, Integer value2) {
            addCriterion("factoryId between", value1, value2, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactoryidNotBetween(Integer value1, Integer value2) {
            addCriterion("factoryId not between", value1, value2, "factoryid");
            return (Criteria) this;
        }

        public Criteria andFactorynoIsNull() {
            addCriterion("factoryNo is null");
            return (Criteria) this;
        }

        public Criteria andFactorynoIsNotNull() {
            addCriterion("factoryNo is not null");
            return (Criteria) this;
        }

        public Criteria andFactorynoEqualTo(String value) {
            addCriterion("factoryNo =", value, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoNotEqualTo(String value) {
            addCriterion("factoryNo <>", value, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoGreaterThan(String value) {
            addCriterion("factoryNo >", value, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoGreaterThanOrEqualTo(String value) {
            addCriterion("factoryNo >=", value, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoLessThan(String value) {
            addCriterion("factoryNo <", value, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoLessThanOrEqualTo(String value) {
            addCriterion("factoryNo <=", value, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoLike(String value) {
            addCriterion("factoryNo like", value, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoNotLike(String value) {
            addCriterion("factoryNo not like", value, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoIn(List<String> values) {
            addCriterion("factoryNo in", values, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoNotIn(List<String> values) {
            addCriterion("factoryNo not in", values, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoBetween(String value1, String value2) {
            addCriterion("factoryNo between", value1, value2, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynoNotBetween(String value1, String value2) {
            addCriterion("factoryNo not between", value1, value2, "factoryno");
            return (Criteria) this;
        }

        public Criteria andFactorynameIsNull() {
            addCriterion("factoryName is null");
            return (Criteria) this;
        }

        public Criteria andFactorynameIsNotNull() {
            addCriterion("factoryName is not null");
            return (Criteria) this;
        }

        public Criteria andFactorynameEqualTo(String value) {
            addCriterion("factoryName =", value, "factoryname");
            return (Criteria) this;
        }

        public Criteria andFactorynameNotEqualTo(String value) {
            addCriterion("factoryName <>", value, "factoryname");
            return (Criteria) this;
        }

        public Criteria andFactorynameGreaterThan(String value) {
            addCriterion("factoryName >", value, "factoryname");
            return (Criteria) this;
        }

        public Criteria andFactorynameGreaterThanOrEqualTo(String value) {
            addCriterion("factoryName >=", value, "factoryname");
            return (Criteria) this;
        }

        public Criteria andFactorynameLessThan(String value) {
            addCriterion("factoryName <", value, "factoryname");
            return (Criteria) this;
        }

        public Criteria andFactorynameLessThanOrEqualTo(String value) {
            addCriterion("factoryName <=", value, "factoryname");
            return (Criteria) this;
        }

        public Criteria andFactorynameLike(String value) {
            addCriterion("factoryName like", value, "factoryname");
            return (Criteria) this;
        }

        public Criteria andFactorynameNotLike(String value) {
            addCriterion("factoryName not like", value, "factoryname");
            return (Criteria) this;
        }

        public Criteria andFactorynameIn(List<String> values) {
            addCriterion("factoryName in", values, "factoryname");
            return (Criteria) this;
        }

        public Criteria andFactorynameNotIn(List<String> values) {
            addCriterion("factoryName not in", values, "factoryname");
            return (Criteria) this;
        }

        public Criteria andFactorynameBetween(String value1, String value2) {
            addCriterion("factoryName between", value1, value2, "factoryname");
            return (Criteria) this;
        }

        public Criteria andFactorynameNotBetween(String value1, String value2) {
            addCriterion("factoryName not between", value1, value2, "factoryname");
            return (Criteria) this;
        }

        public Criteria andFactorylinkmanIsNull() {
            addCriterion("factoryLinkMan is null");
            return (Criteria) this;
        }

        public Criteria andFactorylinkmanIsNotNull() {
            addCriterion("factoryLinkMan is not null");
            return (Criteria) this;
        }

        public Criteria andFactorylinkmanEqualTo(String value) {
            addCriterion("factoryLinkMan =", value, "factorylinkman");
            return (Criteria) this;
        }

        public Criteria andFactorylinkmanNotEqualTo(String value) {
            addCriterion("factoryLinkMan <>", value, "factorylinkman");
            return (Criteria) this;
        }

        public Criteria andFactorylinkmanGreaterThan(String value) {
            addCriterion("factoryLinkMan >", value, "factorylinkman");
            return (Criteria) this;
        }

        public Criteria andFactorylinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("factoryLinkMan >=", value, "factorylinkman");
            return (Criteria) this;
        }

        public Criteria andFactorylinkmanLessThan(String value) {
            addCriterion("factoryLinkMan <", value, "factorylinkman");
            return (Criteria) this;
        }

        public Criteria andFactorylinkmanLessThanOrEqualTo(String value) {
            addCriterion("factoryLinkMan <=", value, "factorylinkman");
            return (Criteria) this;
        }

        public Criteria andFactorylinkmanLike(String value) {
            addCriterion("factoryLinkMan like", value, "factorylinkman");
            return (Criteria) this;
        }

        public Criteria andFactorylinkmanNotLike(String value) {
            addCriterion("factoryLinkMan not like", value, "factorylinkman");
            return (Criteria) this;
        }

        public Criteria andFactorylinkmanIn(List<String> values) {
            addCriterion("factoryLinkMan in", values, "factorylinkman");
            return (Criteria) this;
        }

        public Criteria andFactorylinkmanNotIn(List<String> values) {
            addCriterion("factoryLinkMan not in", values, "factorylinkman");
            return (Criteria) this;
        }

        public Criteria andFactorylinkmanBetween(String value1, String value2) {
            addCriterion("factoryLinkMan between", value1, value2, "factorylinkman");
            return (Criteria) this;
        }

        public Criteria andFactorylinkmanNotBetween(String value1, String value2) {
            addCriterion("factoryLinkMan not between", value1, value2, "factorylinkman");
            return (Criteria) this;
        }

        public Criteria andFactorylinktelIsNull() {
            addCriterion("factoryLinkTel is null");
            return (Criteria) this;
        }

        public Criteria andFactorylinktelIsNotNull() {
            addCriterion("factoryLinkTel is not null");
            return (Criteria) this;
        }

        public Criteria andFactorylinktelEqualTo(String value) {
            addCriterion("factoryLinkTel =", value, "factorylinktel");
            return (Criteria) this;
        }

        public Criteria andFactorylinktelNotEqualTo(String value) {
            addCriterion("factoryLinkTel <>", value, "factorylinktel");
            return (Criteria) this;
        }

        public Criteria andFactorylinktelGreaterThan(String value) {
            addCriterion("factoryLinkTel >", value, "factorylinktel");
            return (Criteria) this;
        }

        public Criteria andFactorylinktelGreaterThanOrEqualTo(String value) {
            addCriterion("factoryLinkTel >=", value, "factorylinktel");
            return (Criteria) this;
        }

        public Criteria andFactorylinktelLessThan(String value) {
            addCriterion("factoryLinkTel <", value, "factorylinktel");
            return (Criteria) this;
        }

        public Criteria andFactorylinktelLessThanOrEqualTo(String value) {
            addCriterion("factoryLinkTel <=", value, "factorylinktel");
            return (Criteria) this;
        }

        public Criteria andFactorylinktelLike(String value) {
            addCriterion("factoryLinkTel like", value, "factorylinktel");
            return (Criteria) this;
        }

        public Criteria andFactorylinktelNotLike(String value) {
            addCriterion("factoryLinkTel not like", value, "factorylinktel");
            return (Criteria) this;
        }

        public Criteria andFactorylinktelIn(List<String> values) {
            addCriterion("factoryLinkTel in", values, "factorylinktel");
            return (Criteria) this;
        }

        public Criteria andFactorylinktelNotIn(List<String> values) {
            addCriterion("factoryLinkTel not in", values, "factorylinktel");
            return (Criteria) this;
        }

        public Criteria andFactorylinktelBetween(String value1, String value2) {
            addCriterion("factoryLinkTel between", value1, value2, "factorylinktel");
            return (Criteria) this;
        }

        public Criteria andFactorylinktelNotBetween(String value1, String value2) {
            addCriterion("factoryLinkTel not between", value1, value2, "factorylinktel");
            return (Criteria) this;
        }

        public Criteria andFactorymailcodeIsNull() {
            addCriterion("factoryMailCode is null");
            return (Criteria) this;
        }

        public Criteria andFactorymailcodeIsNotNull() {
            addCriterion("factoryMailCode is not null");
            return (Criteria) this;
        }

        public Criteria andFactorymailcodeEqualTo(String value) {
            addCriterion("factoryMailCode =", value, "factorymailcode");
            return (Criteria) this;
        }

        public Criteria andFactorymailcodeNotEqualTo(String value) {
            addCriterion("factoryMailCode <>", value, "factorymailcode");
            return (Criteria) this;
        }

        public Criteria andFactorymailcodeGreaterThan(String value) {
            addCriterion("factoryMailCode >", value, "factorymailcode");
            return (Criteria) this;
        }

        public Criteria andFactorymailcodeGreaterThanOrEqualTo(String value) {
            addCriterion("factoryMailCode >=", value, "factorymailcode");
            return (Criteria) this;
        }

        public Criteria andFactorymailcodeLessThan(String value) {
            addCriterion("factoryMailCode <", value, "factorymailcode");
            return (Criteria) this;
        }

        public Criteria andFactorymailcodeLessThanOrEqualTo(String value) {
            addCriterion("factoryMailCode <=", value, "factorymailcode");
            return (Criteria) this;
        }

        public Criteria andFactorymailcodeLike(String value) {
            addCriterion("factoryMailCode like", value, "factorymailcode");
            return (Criteria) this;
        }

        public Criteria andFactorymailcodeNotLike(String value) {
            addCriterion("factoryMailCode not like", value, "factorymailcode");
            return (Criteria) this;
        }

        public Criteria andFactorymailcodeIn(List<String> values) {
            addCriterion("factoryMailCode in", values, "factorymailcode");
            return (Criteria) this;
        }

        public Criteria andFactorymailcodeNotIn(List<String> values) {
            addCriterion("factoryMailCode not in", values, "factorymailcode");
            return (Criteria) this;
        }

        public Criteria andFactorymailcodeBetween(String value1, String value2) {
            addCriterion("factoryMailCode between", value1, value2, "factorymailcode");
            return (Criteria) this;
        }

        public Criteria andFactorymailcodeNotBetween(String value1, String value2) {
            addCriterion("factoryMailCode not between", value1, value2, "factorymailcode");
            return (Criteria) this;
        }

        public Criteria andFactoryaddressIsNull() {
            addCriterion("factoryAddress is null");
            return (Criteria) this;
        }

        public Criteria andFactoryaddressIsNotNull() {
            addCriterion("factoryAddress is not null");
            return (Criteria) this;
        }

        public Criteria andFactoryaddressEqualTo(String value) {
            addCriterion("factoryAddress =", value, "factoryaddress");
            return (Criteria) this;
        }

        public Criteria andFactoryaddressNotEqualTo(String value) {
            addCriterion("factoryAddress <>", value, "factoryaddress");
            return (Criteria) this;
        }

        public Criteria andFactoryaddressGreaterThan(String value) {
            addCriterion("factoryAddress >", value, "factoryaddress");
            return (Criteria) this;
        }

        public Criteria andFactoryaddressGreaterThanOrEqualTo(String value) {
            addCriterion("factoryAddress >=", value, "factoryaddress");
            return (Criteria) this;
        }

        public Criteria andFactoryaddressLessThan(String value) {
            addCriterion("factoryAddress <", value, "factoryaddress");
            return (Criteria) this;
        }

        public Criteria andFactoryaddressLessThanOrEqualTo(String value) {
            addCriterion("factoryAddress <=", value, "factoryaddress");
            return (Criteria) this;
        }

        public Criteria andFactoryaddressLike(String value) {
            addCriterion("factoryAddress like", value, "factoryaddress");
            return (Criteria) this;
        }

        public Criteria andFactoryaddressNotLike(String value) {
            addCriterion("factoryAddress not like", value, "factoryaddress");
            return (Criteria) this;
        }

        public Criteria andFactoryaddressIn(List<String> values) {
            addCriterion("factoryAddress in", values, "factoryaddress");
            return (Criteria) this;
        }

        public Criteria andFactoryaddressNotIn(List<String> values) {
            addCriterion("factoryAddress not in", values, "factoryaddress");
            return (Criteria) this;
        }

        public Criteria andFactoryaddressBetween(String value1, String value2) {
            addCriterion("factoryAddress between", value1, value2, "factoryaddress");
            return (Criteria) this;
        }

        public Criteria andFactoryaddressNotBetween(String value1, String value2) {
            addCriterion("factoryAddress not between", value1, value2, "factoryaddress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table factories
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 16 21:19:55 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table factories
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}