package edu.black.model;

public class Factories {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.factoryId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer factoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.factoryNo
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String factoryno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.factoryName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String factoryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.factoryLinkMan
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String factorylinkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.factoryLinkTel
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String factorylinktel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.factoryMailCode
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String factorymailcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.factoryAddress
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String factoryaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.factoryId
     *
     * @return the value of factories.factoryId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getFactoryid() {
        return factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.factoryId
     *
     * @param factoryid the value for factories.factoryId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setFactoryid(Integer factoryid) {
        this.factoryid = factoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.factoryNo
     *
     * @return the value of factories.factoryNo
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getFactoryno() {
        return factoryno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.factoryNo
     *
     * @param factoryno the value for factories.factoryNo
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setFactoryno(String factoryno) {
        this.factoryno = factoryno == null ? null : factoryno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.factoryName
     *
     * @return the value of factories.factoryName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getFactoryname() {
        return factoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.factoryName
     *
     * @param factoryname the value for factories.factoryName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setFactoryname(String factoryname) {
        this.factoryname = factoryname == null ? null : factoryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.factoryLinkMan
     *
     * @return the value of factories.factoryLinkMan
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getFactorylinkman() {
        return factorylinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.factoryLinkMan
     *
     * @param factorylinkman the value for factories.factoryLinkMan
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setFactorylinkman(String factorylinkman) {
        this.factorylinkman = factorylinkman == null ? null : factorylinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.factoryLinkTel
     *
     * @return the value of factories.factoryLinkTel
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getFactorylinktel() {
        return factorylinktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.factoryLinkTel
     *
     * @param factorylinktel the value for factories.factoryLinkTel
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setFactorylinktel(String factorylinktel) {
        this.factorylinktel = factorylinktel == null ? null : factorylinktel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.factoryMailCode
     *
     * @return the value of factories.factoryMailCode
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getFactorymailcode() {
        return factorymailcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.factoryMailCode
     *
     * @param factorymailcode the value for factories.factoryMailCode
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setFactorymailcode(String factorymailcode) {
        this.factorymailcode = factorymailcode == null ? null : factorymailcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.factoryAddress
     *
     * @return the value of factories.factoryAddress
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getFactoryaddress() {
        return factoryaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.factoryAddress
     *
     * @param factoryaddress the value for factories.factoryAddress
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setFactoryaddress(String factoryaddress) {
        this.factoryaddress = factoryaddress == null ? null : factoryaddress.trim();
    }
}