package edu.black.model;

public class Feedbacks {
    private Clients client;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbacks.feedbackId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer feedbackid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbacks.feedbackClientId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer feedbackclientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbacks.feedbackDate
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String feedbackdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbacks.feedbackEvent
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String feedbackevent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbacks.feedbackLog
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String feedbacklog;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbacks.feedbackId
     *
     * @return the value of feedbacks.feedbackId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getFeedbackid() {
        return feedbackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbacks.feedbackId
     *
     * @param feedbackid the value for feedbacks.feedbackId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setFeedbackid(Integer feedbackid) {
        this.feedbackid = feedbackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbacks.feedbackClientId
     *
     * @return the value of feedbacks.feedbackClientId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getFeedbackclientid() {
        return feedbackclientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbacks.feedbackClientId
     *
     * @param feedbackclientid the value for feedbacks.feedbackClientId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setFeedbackclientid(Integer feedbackclientid) {
        this.feedbackclientid = feedbackclientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbacks.feedbackDate
     *
     * @return the value of feedbacks.feedbackDate
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getFeedbackdate() {
        return feedbackdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbacks.feedbackDate
     *
     * @param feedbackdate the value for feedbacks.feedbackDate
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setFeedbackdate(String feedbackdate) {
        this.feedbackdate = feedbackdate == null ? null : feedbackdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbacks.feedbackEvent
     *
     * @return the value of feedbacks.feedbackEvent
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getFeedbackevent() {
        return feedbackevent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbacks.feedbackEvent
     *
     * @param feedbackevent the value for feedbacks.feedbackEvent
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setFeedbackevent(String feedbackevent) {
        this.feedbackevent = feedbackevent == null ? null : feedbackevent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbacks.feedbackLog
     *
     * @return the value of feedbacks.feedbackLog
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getFeedbacklog() {
        return feedbacklog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbacks.feedbackLog
     *
     * @param feedbacklog the value for feedbacks.feedbackLog
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setFeedbacklog(String feedbacklog) {
        this.feedbacklog = feedbacklog == null ? null : feedbacklog.trim();
    }

    public Clients getClient() {
        return client;
    }

    public void setClient(Clients client) {
        this.client = client;
    }
}