package edu.black.model;

import java.math.BigDecimal;
import java.util.Date;

public class Orders {
    private Integer orderamount;
    private String orderdescription;
    private Cars  car;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderClientId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer orderclientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderCarId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer ordercarid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderCreateDate
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Date ordercreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderStatus
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String orderstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderLocation
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String orderlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderPrice
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private BigDecimal orderprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderId
     *
     * @return the value of orders.orderId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderId
     *
     * @param orderid the value for orders.orderId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderClientId
     *
     * @return the value of orders.orderClientId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getOrderclientid() {
        return orderclientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderClientId
     *
     * @param orderclientid the value for orders.orderClientId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setOrderclientid(Integer orderclientid) {
        this.orderclientid = orderclientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderCarId
     *
     * @return the value of orders.orderCarId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getOrdercarid() {
        return ordercarid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderCarId
     *
     * @param ordercarid the value for orders.orderCarId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setOrdercarid(Integer ordercarid) {
        this.ordercarid = ordercarid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderCreateDate
     *
     * @return the value of orders.orderCreateDate
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Date getOrdercreatedate() {
        return ordercreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderCreateDate
     *
     * @param ordercreatedate the value for orders.orderCreateDate
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setOrdercreatedate(Date ordercreatedate) {
        this.ordercreatedate = ordercreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderStatus
     *
     * @return the value of orders.orderStatus
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderStatus
     *
     * @param orderstatus the value for orders.orderStatus
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setOrderstatus(String orderstatus) {
        this.orderstatus = orderstatus == null ? null : orderstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderLocation
     *
     * @return the value of orders.orderLocation
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getOrderlocation() {
        return orderlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderLocation
     *
     * @param orderlocation the value for orders.orderLocation
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setOrderlocation(String orderlocation) {
        this.orderlocation = orderlocation == null ? null : orderlocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderPrice
     *
     * @return the value of orders.orderPrice
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public BigDecimal getOrderprice() {
        return orderprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderPrice
     *
     * @param orderprice the value for orders.orderPrice
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setOrderprice(BigDecimal orderprice) {
        this.orderprice = orderprice;
    }

    public Integer getOrderamount() {
        return orderamount;
    }

    public void setOrderamount(Integer orderamount) {
        this.orderamount = orderamount;
    }

    public String getOrderdescription() {
        return orderdescription;
    }

    public void setOrderdescription(String orderdescription) {
        this.orderdescription = orderdescription;
    }

    public Cars getCar() {
        return car;
    }

    public void setCar(Cars car) {
        this.car = car;
    }
}