package edu.black.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrdersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public OrdersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderId is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderId is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(Integer value) {
            addCriterion("orderId =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(Integer value) {
            addCriterion("orderId <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(Integer value) {
            addCriterion("orderId >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderId >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(Integer value) {
            addCriterion("orderId <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(Integer value) {
            addCriterion("orderId <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<Integer> values) {
            addCriterion("orderId in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<Integer> values) {
            addCriterion("orderId not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(Integer value1, Integer value2) {
            addCriterion("orderId between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(Integer value1, Integer value2) {
            addCriterion("orderId not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderclientidIsNull() {
            addCriterion("orderClientId is null");
            return (Criteria) this;
        }

        public Criteria andOrderclientidIsNotNull() {
            addCriterion("orderClientId is not null");
            return (Criteria) this;
        }

        public Criteria andOrderclientidEqualTo(Integer value) {
            addCriterion("orderClientId =", value, "orderclientid");
            return (Criteria) this;
        }

        public Criteria andOrderclientidNotEqualTo(Integer value) {
            addCriterion("orderClientId <>", value, "orderclientid");
            return (Criteria) this;
        }

        public Criteria andOrderclientidGreaterThan(Integer value) {
            addCriterion("orderClientId >", value, "orderclientid");
            return (Criteria) this;
        }

        public Criteria andOrderclientidGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderClientId >=", value, "orderclientid");
            return (Criteria) this;
        }

        public Criteria andOrderclientidLessThan(Integer value) {
            addCriterion("orderClientId <", value, "orderclientid");
            return (Criteria) this;
        }

        public Criteria andOrderclientidLessThanOrEqualTo(Integer value) {
            addCriterion("orderClientId <=", value, "orderclientid");
            return (Criteria) this;
        }

        public Criteria andOrderclientidIn(List<Integer> values) {
            addCriterion("orderClientId in", values, "orderclientid");
            return (Criteria) this;
        }

        public Criteria andOrderclientidNotIn(List<Integer> values) {
            addCriterion("orderClientId not in", values, "orderclientid");
            return (Criteria) this;
        }

        public Criteria andOrderclientidBetween(Integer value1, Integer value2) {
            addCriterion("orderClientId between", value1, value2, "orderclientid");
            return (Criteria) this;
        }

        public Criteria andOrderclientidNotBetween(Integer value1, Integer value2) {
            addCriterion("orderClientId not between", value1, value2, "orderclientid");
            return (Criteria) this;
        }

        public Criteria andOrdercaridIsNull() {
            addCriterion("orderCarId is null");
            return (Criteria) this;
        }

        public Criteria andOrdercaridIsNotNull() {
            addCriterion("orderCarId is not null");
            return (Criteria) this;
        }

        public Criteria andOrdercaridEqualTo(Integer value) {
            addCriterion("orderCarId =", value, "ordercarid");
            return (Criteria) this;
        }

        public Criteria andOrdercaridNotEqualTo(Integer value) {
            addCriterion("orderCarId <>", value, "ordercarid");
            return (Criteria) this;
        }

        public Criteria andOrdercaridGreaterThan(Integer value) {
            addCriterion("orderCarId >", value, "ordercarid");
            return (Criteria) this;
        }

        public Criteria andOrdercaridGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderCarId >=", value, "ordercarid");
            return (Criteria) this;
        }

        public Criteria andOrdercaridLessThan(Integer value) {
            addCriterion("orderCarId <", value, "ordercarid");
            return (Criteria) this;
        }

        public Criteria andOrdercaridLessThanOrEqualTo(Integer value) {
            addCriterion("orderCarId <=", value, "ordercarid");
            return (Criteria) this;
        }

        public Criteria andOrdercaridIn(List<Integer> values) {
            addCriterion("orderCarId in", values, "ordercarid");
            return (Criteria) this;
        }

        public Criteria andOrdercaridNotIn(List<Integer> values) {
            addCriterion("orderCarId not in", values, "ordercarid");
            return (Criteria) this;
        }

        public Criteria andOrdercaridBetween(Integer value1, Integer value2) {
            addCriterion("orderCarId between", value1, value2, "ordercarid");
            return (Criteria) this;
        }

        public Criteria andOrdercaridNotBetween(Integer value1, Integer value2) {
            addCriterion("orderCarId not between", value1, value2, "ordercarid");
            return (Criteria) this;
        }

        public Criteria andOrdercreatedateIsNull() {
            addCriterion("orderCreateDate is null");
            return (Criteria) this;
        }

        public Criteria andOrdercreatedateIsNotNull() {
            addCriterion("orderCreateDate is not null");
            return (Criteria) this;
        }

        public Criteria andOrdercreatedateEqualTo(Date value) {
            addCriterion("orderCreateDate =", value, "ordercreatedate");
            return (Criteria) this;
        }

        public Criteria andOrdercreatedateNotEqualTo(Date value) {
            addCriterion("orderCreateDate <>", value, "ordercreatedate");
            return (Criteria) this;
        }

        public Criteria andOrdercreatedateGreaterThan(Date value) {
            addCriterion("orderCreateDate >", value, "ordercreatedate");
            return (Criteria) this;
        }

        public Criteria andOrdercreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("orderCreateDate >=", value, "ordercreatedate");
            return (Criteria) this;
        }

        public Criteria andOrdercreatedateLessThan(Date value) {
            addCriterion("orderCreateDate <", value, "ordercreatedate");
            return (Criteria) this;
        }

        public Criteria andOrdercreatedateLessThanOrEqualTo(Date value) {
            addCriterion("orderCreateDate <=", value, "ordercreatedate");
            return (Criteria) this;
        }

        public Criteria andOrdercreatedateIn(List<Date> values) {
            addCriterion("orderCreateDate in", values, "ordercreatedate");
            return (Criteria) this;
        }

        public Criteria andOrdercreatedateNotIn(List<Date> values) {
            addCriterion("orderCreateDate not in", values, "ordercreatedate");
            return (Criteria) this;
        }

        public Criteria andOrdercreatedateBetween(Date value1, Date value2) {
            addCriterion("orderCreateDate between", value1, value2, "ordercreatedate");
            return (Criteria) this;
        }

        public Criteria andOrdercreatedateNotBetween(Date value1, Date value2) {
            addCriterion("orderCreateDate not between", value1, value2, "ordercreatedate");
            return (Criteria) this;
        }

        public Criteria andOrderstatusIsNull() {
            addCriterion("orderStatus is null");
            return (Criteria) this;
        }

        public Criteria andOrderstatusIsNotNull() {
            addCriterion("orderStatus is not null");
            return (Criteria) this;
        }

        public Criteria andOrderstatusEqualTo(String value) {
            addCriterion("orderStatus =", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusNotEqualTo(String value) {
            addCriterion("orderStatus <>", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusGreaterThan(String value) {
            addCriterion("orderStatus >", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusGreaterThanOrEqualTo(String value) {
            addCriterion("orderStatus >=", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusLessThan(String value) {
            addCriterion("orderStatus <", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusLessThanOrEqualTo(String value) {
            addCriterion("orderStatus <=", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusLike(String value) {
            addCriterion("orderStatus like", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusNotLike(String value) {
            addCriterion("orderStatus not like", value, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusIn(List<String> values) {
            addCriterion("orderStatus in", values, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusNotIn(List<String> values) {
            addCriterion("orderStatus not in", values, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusBetween(String value1, String value2) {
            addCriterion("orderStatus between", value1, value2, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderstatusNotBetween(String value1, String value2) {
            addCriterion("orderStatus not between", value1, value2, "orderstatus");
            return (Criteria) this;
        }

        public Criteria andOrderlocationIsNull() {
            addCriterion("orderLocation is null");
            return (Criteria) this;
        }

        public Criteria andOrderlocationIsNotNull() {
            addCriterion("orderLocation is not null");
            return (Criteria) this;
        }

        public Criteria andOrderlocationEqualTo(String value) {
            addCriterion("orderLocation =", value, "orderlocation");
            return (Criteria) this;
        }

        public Criteria andOrderlocationNotEqualTo(String value) {
            addCriterion("orderLocation <>", value, "orderlocation");
            return (Criteria) this;
        }

        public Criteria andOrderlocationGreaterThan(String value) {
            addCriterion("orderLocation >", value, "orderlocation");
            return (Criteria) this;
        }

        public Criteria andOrderlocationGreaterThanOrEqualTo(String value) {
            addCriterion("orderLocation >=", value, "orderlocation");
            return (Criteria) this;
        }

        public Criteria andOrderlocationLessThan(String value) {
            addCriterion("orderLocation <", value, "orderlocation");
            return (Criteria) this;
        }

        public Criteria andOrderlocationLessThanOrEqualTo(String value) {
            addCriterion("orderLocation <=", value, "orderlocation");
            return (Criteria) this;
        }

        public Criteria andOrderlocationLike(String value) {
            addCriterion("orderLocation like", value, "orderlocation");
            return (Criteria) this;
        }

        public Criteria andOrderlocationNotLike(String value) {
            addCriterion("orderLocation not like", value, "orderlocation");
            return (Criteria) this;
        }

        public Criteria andOrderlocationIn(List<String> values) {
            addCriterion("orderLocation in", values, "orderlocation");
            return (Criteria) this;
        }

        public Criteria andOrderlocationNotIn(List<String> values) {
            addCriterion("orderLocation not in", values, "orderlocation");
            return (Criteria) this;
        }

        public Criteria andOrderlocationBetween(String value1, String value2) {
            addCriterion("orderLocation between", value1, value2, "orderlocation");
            return (Criteria) this;
        }

        public Criteria andOrderlocationNotBetween(String value1, String value2) {
            addCriterion("orderLocation not between", value1, value2, "orderlocation");
            return (Criteria) this;
        }

        public Criteria andOrderpriceIsNull() {
            addCriterion("orderPrice is null");
            return (Criteria) this;
        }

        public Criteria andOrderpriceIsNotNull() {
            addCriterion("orderPrice is not null");
            return (Criteria) this;
        }

        public Criteria andOrderpriceEqualTo(BigDecimal value) {
            addCriterion("orderPrice =", value, "orderprice");
            return (Criteria) this;
        }

        public Criteria andOrderpriceNotEqualTo(BigDecimal value) {
            addCriterion("orderPrice <>", value, "orderprice");
            return (Criteria) this;
        }

        public Criteria andOrderpriceGreaterThan(BigDecimal value) {
            addCriterion("orderPrice >", value, "orderprice");
            return (Criteria) this;
        }

        public Criteria andOrderpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("orderPrice >=", value, "orderprice");
            return (Criteria) this;
        }

        public Criteria andOrderpriceLessThan(BigDecimal value) {
            addCriterion("orderPrice <", value, "orderprice");
            return (Criteria) this;
        }

        public Criteria andOrderpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("orderPrice <=", value, "orderprice");
            return (Criteria) this;
        }

        public Criteria andOrderpriceIn(List<BigDecimal> values) {
            addCriterion("orderPrice in", values, "orderprice");
            return (Criteria) this;
        }

        public Criteria andOrderpriceNotIn(List<BigDecimal> values) {
            addCriterion("orderPrice not in", values, "orderprice");
            return (Criteria) this;
        }

        public Criteria andOrderpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("orderPrice between", value1, value2, "orderprice");
            return (Criteria) this;
        }

        public Criteria andOrderpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("orderPrice not between", value1, value2, "orderprice");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 16 21:19:55 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}