package edu.black.model;

public class Rolesauthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolesauthority.roleId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rolesauthority.authorityId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer authorityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolesauthority.roleId
     *
     * @return the value of rolesauthority.roleId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolesauthority.roleId
     *
     * @param roleid the value for rolesauthority.roleId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rolesauthority.authorityId
     *
     * @return the value of rolesauthority.authorityId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getAuthorityid() {
        return authorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rolesauthority.authorityId
     *
     * @param authorityid the value for rolesauthority.authorityId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setAuthorityid(Integer authorityid) {
        this.authorityid = authorityid;
    }
}