package edu.black.model;

import java.util.List;

public class Roles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.roleId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.roleName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.roleDescription
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String roledescription;

    /**
     * 角色对应的权限
     */
    private List<Authority> authorities;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.roleId
     *
     * @return the value of roles.roleId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.roleId
     *
     * @param roleid the value for roles.roleId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.roleName
     *
     * @return the value of roles.roleName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.roleName
     *
     * @param rolename the value for roles.roleName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.roleDescription
     *
     * @return the value of roles.roleDescription
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getRoledescription() {
        return roledescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.roleDescription
     *
     * @param roledescription the value for roles.roleDescription
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setRoledescription(String roledescription) {
        this.roledescription = roledescription == null ? null : roledescription.trim();
    }

    public List<Authority> getAuthorities() {
        return authorities;
    }

    public void setAuthorities(List<Authority> authorities) {
        this.authorities = authorities;
    }
}