package edu.black.model;

public class Store {
    private Integer prewarehouseid;
    private Integer amount;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.warehouseId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer warehouseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.carId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer carid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.warehouseId
     *
     * @return the value of store.warehouseId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getWarehouseid() {
        return warehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.warehouseId
     *
     * @param warehouseid the value for store.warehouseId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setWarehouseid(Integer warehouseid) {
        this.warehouseid = warehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.carId
     *
     * @return the value of store.carId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.carId
     *
     * @param carid the value for store.carId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setCarid(Integer carid) {
        this.carid = carid;
    }


    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public Integer getPrewarehouseid() {
        return prewarehouseid;
    }

    public void setPrewarehouseid(Integer prewarehouseid) {
        this.prewarehouseid = prewarehouseid;
    }
}