package edu.black.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class Users {

    public Users() {
        authorities = new ArrayList<>();
    }

    /**
     * 用户角色
     */
    private List<Roles> roles;

    /**
     * 用户拥有的权限
     */
    private List<Authority> authorities;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.userId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.userName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.userAccessName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String useraccessname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.userAccessPassword
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String useraccesspassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.userGender
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String usergender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.userTel
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private String usertel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.userId
     *
     * @return the value of users.userId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.userId
     *
     * @param userid the value for users.userId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.userName
     *
     * @return the value of users.userName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.userName
     *
     * @param username the value for users.userName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.userAccessName
     *
     * @return the value of users.userAccessName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getUseraccessname() {
        return useraccessname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.userAccessName
     *
     * @param useraccessname the value for users.userAccessName
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setUseraccessname(String useraccessname) {
        this.useraccessname = useraccessname == null ? null : useraccessname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.userAccessPassword
     *
     * @return the value of users.userAccessPassword
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getUseraccesspassword() {
        return useraccesspassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.userAccessPassword
     *
     * @param useraccesspassword the value for users.userAccessPassword
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setUseraccesspassword(String useraccesspassword) {
        this.useraccesspassword = useraccesspassword == null ? null : useraccesspassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.userGender
     *
     * @return the value of users.userGender
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getUsergender() {
        return usergender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.userGender
     *
     * @param usergender the value for users.userGender
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setUsergender(String usergender) {
        this.usergender = usergender == null ? null : usergender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.userTel
     *
     * @return the value of users.userTel
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public String getUsertel() {
        return usertel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.userTel
     *
     * @param usertel the value for users.userTel
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setUsertel(String usertel) {
        this.usertel = usertel == null ? null : usertel.trim();
    }

    public List<Roles> getRoles() {
        return roles;
    }

    public void setRoles(List<Roles> roles) {
        this.roles = roles;
    }

    public List<Authority> getAuthorities() {
        return authorities;
    }

    public void setAuthorities(List<Authority> authorities) {
        this.authorities = authorities;
    }
}