package edu.black.model;

public class Usersrole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersrole.userId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersrole.roleId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersrole.userId
     *
     * @return the value of usersrole.userId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersrole.userId
     *
     * @param userid the value for usersrole.userId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersrole.roleId
     *
     * @return the value of usersrole.roleId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersrole.roleId
     *
     * @param roleid the value for usersrole.roleId
     *
     * @mbg.generated Mon Apr 16 21:19:55 CST 2018
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}