package edu.black.model;

import java.util.List;

public class Warehouse {
    /**
     * 车库内汽车
     */
    private List<Cars> cars;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.warehouseId
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    private Integer warehouseid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.warehouseName
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    private String warehousename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.warehouseLocation
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    private String warehouselocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.warehouseMaxStore
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    private Integer warehousemaxstore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.warehouseRemainStore
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    private Integer warehouseremainstore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.warehouseId
     *
     * @return the value of warehouse.warehouseId
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public Integer getWarehouseid() {
        return warehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.warehouseId
     *
     * @param warehouseid the value for warehouse.warehouseId
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public void setWarehouseid(Integer warehouseid) {
        this.warehouseid = warehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.warehouseName
     *
     * @return the value of warehouse.warehouseName
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public String getWarehousename() {
        return warehousename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.warehouseName
     *
     * @param warehousename the value for warehouse.warehouseName
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public void setWarehousename(String warehousename) {
        this.warehousename = warehousename == null ? null : warehousename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.warehouseLocation
     *
     * @return the value of warehouse.warehouseLocation
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public String getWarehouselocation() {
        return warehouselocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.warehouseLocation
     *
     * @param warehouselocation the value for warehouse.warehouseLocation
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public void setWarehouselocation(String warehouselocation) {
        this.warehouselocation = warehouselocation == null ? null : warehouselocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.warehouseMaxStore
     *
     * @return the value of warehouse.warehouseMaxStore
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public Integer getWarehousemaxstore() {
        return warehousemaxstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.warehouseMaxStore
     *
     * @param warehousemaxstore the value for warehouse.warehouseMaxStore
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public void setWarehousemaxstore(Integer warehousemaxstore) {
        this.warehousemaxstore = warehousemaxstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.warehouseRemainStore
     *
     * @return the value of warehouse.warehouseRemainStore
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public Integer getWarehouseremainstore() {
        return warehouseremainstore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.warehouseRemainStore
     *
     * @param warehouseremainstore the value for warehouse.warehouseRemainStore
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public void setWarehouseremainstore(Integer warehouseremainstore) {
        this.warehouseremainstore = warehouseremainstore;
    }

    public List<Cars> getCars() {
        return cars;
    }

    public void setCars(List<Cars> cars) {
        this.cars = cars;
    }
}