package edu.black.model;

import java.util.ArrayList;
import java.util.List;

public class WarehouseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public WarehouseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWarehouseidIsNull() {
            addCriterion("warehouseId is null");
            return (Criteria) this;
        }

        public Criteria andWarehouseidIsNotNull() {
            addCriterion("warehouseId is not null");
            return (Criteria) this;
        }

        public Criteria andWarehouseidEqualTo(Integer value) {
            addCriterion("warehouseId =", value, "warehouseid");
            return (Criteria) this;
        }

        public Criteria andWarehouseidNotEqualTo(Integer value) {
            addCriterion("warehouseId <>", value, "warehouseid");
            return (Criteria) this;
        }

        public Criteria andWarehouseidGreaterThan(Integer value) {
            addCriterion("warehouseId >", value, "warehouseid");
            return (Criteria) this;
        }

        public Criteria andWarehouseidGreaterThanOrEqualTo(Integer value) {
            addCriterion("warehouseId >=", value, "warehouseid");
            return (Criteria) this;
        }

        public Criteria andWarehouseidLessThan(Integer value) {
            addCriterion("warehouseId <", value, "warehouseid");
            return (Criteria) this;
        }

        public Criteria andWarehouseidLessThanOrEqualTo(Integer value) {
            addCriterion("warehouseId <=", value, "warehouseid");
            return (Criteria) this;
        }

        public Criteria andWarehouseidIn(List<Integer> values) {
            addCriterion("warehouseId in", values, "warehouseid");
            return (Criteria) this;
        }

        public Criteria andWarehouseidNotIn(List<Integer> values) {
            addCriterion("warehouseId not in", values, "warehouseid");
            return (Criteria) this;
        }

        public Criteria andWarehouseidBetween(Integer value1, Integer value2) {
            addCriterion("warehouseId between", value1, value2, "warehouseid");
            return (Criteria) this;
        }

        public Criteria andWarehouseidNotBetween(Integer value1, Integer value2) {
            addCriterion("warehouseId not between", value1, value2, "warehouseid");
            return (Criteria) this;
        }

        public Criteria andWarehousenameIsNull() {
            addCriterion("warehouseName is null");
            return (Criteria) this;
        }

        public Criteria andWarehousenameIsNotNull() {
            addCriterion("warehouseName is not null");
            return (Criteria) this;
        }

        public Criteria andWarehousenameEqualTo(String value) {
            addCriterion("warehouseName =", value, "warehousename");
            return (Criteria) this;
        }

        public Criteria andWarehousenameNotEqualTo(String value) {
            addCriterion("warehouseName <>", value, "warehousename");
            return (Criteria) this;
        }

        public Criteria andWarehousenameGreaterThan(String value) {
            addCriterion("warehouseName >", value, "warehousename");
            return (Criteria) this;
        }

        public Criteria andWarehousenameGreaterThanOrEqualTo(String value) {
            addCriterion("warehouseName >=", value, "warehousename");
            return (Criteria) this;
        }

        public Criteria andWarehousenameLessThan(String value) {
            addCriterion("warehouseName <", value, "warehousename");
            return (Criteria) this;
        }

        public Criteria andWarehousenameLessThanOrEqualTo(String value) {
            addCriterion("warehouseName <=", value, "warehousename");
            return (Criteria) this;
        }

        public Criteria andWarehousenameLike(String value) {
            addCriterion("warehouseName like", value, "warehousename");
            return (Criteria) this;
        }

        public Criteria andWarehousenameNotLike(String value) {
            addCriterion("warehouseName not like", value, "warehousename");
            return (Criteria) this;
        }

        public Criteria andWarehousenameIn(List<String> values) {
            addCriterion("warehouseName in", values, "warehousename");
            return (Criteria) this;
        }

        public Criteria andWarehousenameNotIn(List<String> values) {
            addCriterion("warehouseName not in", values, "warehousename");
            return (Criteria) this;
        }

        public Criteria andWarehousenameBetween(String value1, String value2) {
            addCriterion("warehouseName between", value1, value2, "warehousename");
            return (Criteria) this;
        }

        public Criteria andWarehousenameNotBetween(String value1, String value2) {
            addCriterion("warehouseName not between", value1, value2, "warehousename");
            return (Criteria) this;
        }

        public Criteria andWarehouselocationIsNull() {
            addCriterion("warehouseLocation is null");
            return (Criteria) this;
        }

        public Criteria andWarehouselocationIsNotNull() {
            addCriterion("warehouseLocation is not null");
            return (Criteria) this;
        }

        public Criteria andWarehouselocationEqualTo(String value) {
            addCriterion("warehouseLocation =", value, "warehouselocation");
            return (Criteria) this;
        }

        public Criteria andWarehouselocationNotEqualTo(String value) {
            addCriterion("warehouseLocation <>", value, "warehouselocation");
            return (Criteria) this;
        }

        public Criteria andWarehouselocationGreaterThan(String value) {
            addCriterion("warehouseLocation >", value, "warehouselocation");
            return (Criteria) this;
        }

        public Criteria andWarehouselocationGreaterThanOrEqualTo(String value) {
            addCriterion("warehouseLocation >=", value, "warehouselocation");
            return (Criteria) this;
        }

        public Criteria andWarehouselocationLessThan(String value) {
            addCriterion("warehouseLocation <", value, "warehouselocation");
            return (Criteria) this;
        }

        public Criteria andWarehouselocationLessThanOrEqualTo(String value) {
            addCriterion("warehouseLocation <=", value, "warehouselocation");
            return (Criteria) this;
        }

        public Criteria andWarehouselocationLike(String value) {
            addCriterion("warehouseLocation like", value, "warehouselocation");
            return (Criteria) this;
        }

        public Criteria andWarehouselocationNotLike(String value) {
            addCriterion("warehouseLocation not like", value, "warehouselocation");
            return (Criteria) this;
        }

        public Criteria andWarehouselocationIn(List<String> values) {
            addCriterion("warehouseLocation in", values, "warehouselocation");
            return (Criteria) this;
        }

        public Criteria andWarehouselocationNotIn(List<String> values) {
            addCriterion("warehouseLocation not in", values, "warehouselocation");
            return (Criteria) this;
        }

        public Criteria andWarehouselocationBetween(String value1, String value2) {
            addCriterion("warehouseLocation between", value1, value2, "warehouselocation");
            return (Criteria) this;
        }

        public Criteria andWarehouselocationNotBetween(String value1, String value2) {
            addCriterion("warehouseLocation not between", value1, value2, "warehouselocation");
            return (Criteria) this;
        }

        public Criteria andWarehousemaxstoreIsNull() {
            addCriterion("warehouseMaxStore is null");
            return (Criteria) this;
        }

        public Criteria andWarehousemaxstoreIsNotNull() {
            addCriterion("warehouseMaxStore is not null");
            return (Criteria) this;
        }

        public Criteria andWarehousemaxstoreEqualTo(Integer value) {
            addCriterion("warehouseMaxStore =", value, "warehousemaxstore");
            return (Criteria) this;
        }

        public Criteria andWarehousemaxstoreNotEqualTo(Integer value) {
            addCriterion("warehouseMaxStore <>", value, "warehousemaxstore");
            return (Criteria) this;
        }

        public Criteria andWarehousemaxstoreGreaterThan(Integer value) {
            addCriterion("warehouseMaxStore >", value, "warehousemaxstore");
            return (Criteria) this;
        }

        public Criteria andWarehousemaxstoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("warehouseMaxStore >=", value, "warehousemaxstore");
            return (Criteria) this;
        }

        public Criteria andWarehousemaxstoreLessThan(Integer value) {
            addCriterion("warehouseMaxStore <", value, "warehousemaxstore");
            return (Criteria) this;
        }

        public Criteria andWarehousemaxstoreLessThanOrEqualTo(Integer value) {
            addCriterion("warehouseMaxStore <=", value, "warehousemaxstore");
            return (Criteria) this;
        }

        public Criteria andWarehousemaxstoreIn(List<Integer> values) {
            addCriterion("warehouseMaxStore in", values, "warehousemaxstore");
            return (Criteria) this;
        }

        public Criteria andWarehousemaxstoreNotIn(List<Integer> values) {
            addCriterion("warehouseMaxStore not in", values, "warehousemaxstore");
            return (Criteria) this;
        }

        public Criteria andWarehousemaxstoreBetween(Integer value1, Integer value2) {
            addCriterion("warehouseMaxStore between", value1, value2, "warehousemaxstore");
            return (Criteria) this;
        }

        public Criteria andWarehousemaxstoreNotBetween(Integer value1, Integer value2) {
            addCriterion("warehouseMaxStore not between", value1, value2, "warehousemaxstore");
            return (Criteria) this;
        }

        public Criteria andWarehouseremainstoreIsNull() {
            addCriterion("warehouseRemainStore is null");
            return (Criteria) this;
        }

        public Criteria andWarehouseremainstoreIsNotNull() {
            addCriterion("warehouseRemainStore is not null");
            return (Criteria) this;
        }

        public Criteria andWarehouseremainstoreEqualTo(Integer value) {
            addCriterion("warehouseRemainStore =", value, "warehouseremainstore");
            return (Criteria) this;
        }

        public Criteria andWarehouseremainstoreNotEqualTo(Integer value) {
            addCriterion("warehouseRemainStore <>", value, "warehouseremainstore");
            return (Criteria) this;
        }

        public Criteria andWarehouseremainstoreGreaterThan(Integer value) {
            addCriterion("warehouseRemainStore >", value, "warehouseremainstore");
            return (Criteria) this;
        }

        public Criteria andWarehouseremainstoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("warehouseRemainStore >=", value, "warehouseremainstore");
            return (Criteria) this;
        }

        public Criteria andWarehouseremainstoreLessThan(Integer value) {
            addCriterion("warehouseRemainStore <", value, "warehouseremainstore");
            return (Criteria) this;
        }

        public Criteria andWarehouseremainstoreLessThanOrEqualTo(Integer value) {
            addCriterion("warehouseRemainStore <=", value, "warehouseremainstore");
            return (Criteria) this;
        }

        public Criteria andWarehouseremainstoreIn(List<Integer> values) {
            addCriterion("warehouseRemainStore in", values, "warehouseremainstore");
            return (Criteria) this;
        }

        public Criteria andWarehouseremainstoreNotIn(List<Integer> values) {
            addCriterion("warehouseRemainStore not in", values, "warehouseremainstore");
            return (Criteria) this;
        }

        public Criteria andWarehouseremainstoreBetween(Integer value1, Integer value2) {
            addCriterion("warehouseRemainStore between", value1, value2, "warehouseremainstore");
            return (Criteria) this;
        }

        public Criteria andWarehouseremainstoreNotBetween(Integer value1, Integer value2) {
            addCriterion("warehouseRemainStore not between", value1, value2, "warehouseremainstore");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table warehouse
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 17 17:02:12 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table warehouse
     *
     * @mbg.generated Tue Apr 17 17:02:12 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}